### ISSUE TITLE
ios 支付成功以后，或者取消支付返回app直接退出

### ISSUE THREAD

**Issue by htzhanglong** [charleyw/cordova-plugin-alipay#23]
ios 支付成功以后，或者取消支付返回app直接退出，没有执行到成功或者失败的回调

作者你好 ：
 ios手机的版本是ios9 .1
cordova 版本5.4.1 和 6.0都试了，都是这个问题

对您来说应该就是几行代码问题。

就是返回的时候没有 执行成功失败回调  app直接退出 也没有错误提示

点击支付的时候会有提示：

2016-03-16 17:17:47.502 Hbbeer[238:9814] orderSpec = partner="2088121884426545"&seller_id="dingbohanxxx@qq.com"&out_trade_no="1421161516213317"&subject="测试标题"&body="我是测试内容"&total_fee="0.01"&notify_url="http://your.server.notify.url"&service="mobile.securitypay.pay"&payment_type="1"&_input_charset="utf-8"&it_b_pay="30m"&show_url="m.alipay.com"
2016-03-16 17:17:48.032 Hbbeer[238:9814] THREAD WARNING: ['AliPay'] took '530.517090' ms. Plugin should use a background thread.

支付成功返回  或者取消返回都没有任何信息

还请管理腾出时间帮忙瞅瞅

如果真的很忙可以给您报酬帮忙解决一下，项目就差这个东西了

我的qq ：380491498   加的时候写上github就知道了

**Comment by charleyw** [comment]
不好意思，上周我娃出生了，所以一直没时间看。
我刚才试了一下cordova 6.0，这边是正常的。

还有没更多的log信息？

**Comment by htzhanglong** [comment]
恭喜恭喜  我换个项目试试 非常感谢

**Comment by nn1900** [comment]
也是出现这个问题哈，我用的是cordova 6，是在libc++这个库里面出的问题，空了看下兄弟！感谢。
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0x10de3cc20'
*** First throw call stack:
(0x183d42e38 0x1833a7f80 0x183d49ccc 0x183d46c74 0x183c44d1c 0x189284864 0x1892849d0 0x189724d44 0x188f94490 0x184675980 0x1846753f4 0x18467514c 0x188f950e0 0x184674d50 0x188f94c80 0x188f94ec4 0x188f94c90 0x188e87368 0x188f95014 0x184674d50 0x188f94c80 0x188f94ec4 0x188f94c90 0x188e87368 0x1891ae968 0x188f95014 0x184674d50 0x188f94c80 0x188f94ec4 0x188f94c90 0x188e87368 0x188f95014 0x184674d50 0x188f94c80 0x188f94ec4 0x188f94c90 0x188e87368 0x188f95014 0x184674d50 0x188f94c80 0x188f94ec4 0x188f94c90 0x188e87368 0x188f95014 0x184674d50 0x188f94c80 0x188f94ec4 0x188f94c90 0x188e87368 0x188e86c1c 0x184674d50 0x188e86ac4 0x188e94578 0x1892ebe94 0x1891edec0 0x1891ebfd8 0x18913efd8 0x18914c990 0x188e7e4a4 0x183cf87b0 0x183cf6554 0x183cf6984 0x183c20d10 0x185508088 0x188ef5f70 0x100005bd4 0x1837be8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
